--- #YAML:1.0
name:                Net-Scan-SMTP-Banner
version:             0.02
abstract:            This module permit to grab the banner message from a SMTP server.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0.22
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Matteo Cantoni <mcantoni@nothink.org>
